### ISSUE TITLE
UI issue in Logout Modal - Yes & No buttons are blurred out.

### ISSUE THREAD

**Issue by Rajdeepc** [Rajdeepc/iam-available#3]
1. Yes & No buttons should be inside the modal body. Currently they are blurred out.
2. No button color should be grey instead of red

**Comment by rhythm1920** [comment]
Can I take up this issue??

**Comment by Rajdeepc** [comment]
Go Ahead

**Comment by Rajdeepc** [comment]
@ankitgauri26 yes

**Comment by ankitgauri26** [comment]
I am starting working. Request you to please assign it to me if possible

**Comment by ankitgauri26** [comment]
Solved the issue and created the pull request.
