### ISSUE TITLE
Closing the Modal clicking on X changes state to Not Available - Should stay as Available only

### ISSUE THREAD

**Issue by Rajdeepc** [Rajdeepc/iam-available#5]
Steps:

You are on Available status
Change switch to Not Available > Modal Opens > Close Modal(Dont change anything)

Expected: Should stay as Available only

Actual:Closing the Modal clicking on X changes state to Not Available

**Comment by Varsha-Hardikar** [comment]
I would be working on this issue

**Comment by Rajdeepc** [comment]
@Varsha-Hardikar assigned to you. Please work on this issue and raise a PR to master branch.

**Comment by Rajdeepc** [comment]
Issue solved
